# Generated by Django 3.0.1 on 2020-01-11 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200110_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='expiry_date',
            new_name='last_pay_date',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='next_pay_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[('1', 'Payloop'), ('2', 'Education')], default=1),
        ),
    ]
