# Generated by Django 3.0.1 on 2020-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200111_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Payloop'), (2, 'Education')], default=1),
        ),
    ]
