# Generated by Django 3.0.1 on 2020-01-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200111_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='gellery_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='gellery_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='gellery_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery4',
            field=models.ImageField(blank=True, null=True, upload_to='gellery_images'),
        ),
    ]
