# Generated by Django 3.0.1 on 2020-01-11 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200111_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gellery_images'),
            preserve_default=False,
        ),
    ]
