# Generated by Django 3.0.1 on 2020-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200111_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('highlight', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('activate', models.BooleanField()),
            ],
        ),
    ]
