# Generated by Django 3.0.1 on 2020-01-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_bannertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(max_length=20),
        ),
    ]
