# Generated by Django 3.0.1 on 2020-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200112_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='amount',
        ),
        migrations.AddField(
            model_name='packages',
            name='des',
            field=models.TextField(default='best module package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
