# Generated by Django 3.0.1 on 2020-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200115_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='modules',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
