# Generated by Django 3.0.1 on 2020-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_clientprofile_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
