# Generated by Django 3.0.1 on 2020-01-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_packages_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='p_type',
            field=models.IntegerField(choices=[(1, 'All Package'), (2, 'Custom'), (3, 'Single Package')]),
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
