# Generated by Django 3.0.1 on 2020-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_clientmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodule',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_pay_date',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='next_pay_date',
        ),
        migrations.AddField(
            model_name='clientmodule',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
