# Generated by Django 3.0.1 on 2020-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200131_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('demo_type', models.CharField(choices=[('education', 'Education Modules'), ('ERP', 'Enterprise Resource Planning')], max_length=10)),
            ],
        ),
    ]
