# Generated by Django 3.0.1 on 2020-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_demolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolist',
            name='company_address',
            field=models.TextField(),
        ),
    ]
