# Generated by Django 2.2 on 2020-06-28 17:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200319_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.ImageField(upload_to='product_icons')),
                ('content', ckeditor.fields.RichTextField()),
                ('video', models.CharField(max_length=20)),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
            ],
            options={
                'verbose_name': 'Education Product',
                'verbose_name_plural': 'Education Products',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Payloop')], default=1),
        ),
    ]
