# Generated by Django 2.2 on 2020-06-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200628_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodule',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Education'),
        ),
        migrations.AddField(
            model_name='clientmodule',
            name='module_type',
            field=models.CharField(choices=[('erp', 'ERP'), ('education', 'Education')], default='erp', max_length=12),
        ),
        migrations.AlterField(
            model_name='clientmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
    ]
